# SwiftLint Configuration for wims-ios
# Swift 6.0+, iOS 17+, Swift Testing framework

# Paths to include/exclude
included:
  - Wims/Wims
  - PersistencyLayer/Sources
  - PersistencyLayer/Tests
  - SwiftDataQuery/Sources
  - SwiftDataQuery/Tests

excluded:
  - Wims/Wims.xcodeproj
  - Wims/Wims/Assets.xcassets
  - "**/.build"
  - .build
  - Pods
  - Carthage
  - .git
  - "**/*.derived"

# Enabled Rules
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Disabled Rules
disabled_rules:
  - todo
  - trailing_whitespace
  - trailing_comma
  - implicit_return

# Rule Configurations
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: false

file_length:
  warning: 400
  error: 500
  ignore_comment_only_lines: true

type_body_length:
  warning: 300
  error: 400

function_body_length:
  warning: 50
  error: 100

cyclomatic_complexity:
  warning: 10
  error: 20
  ignores_case_statements: true

nesting:
  type_level:
    warning: 2
    error: 3
  function_level:
    warning: 3
    error: 5

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - i
    - j
    - k
    - x
    - y
    - z
    - vm  # Common for ViewModel

type_name:
  min_length: 3
  max_length: 50

# Custom Rules for Swift Testing (not XCTest)
custom_rules:
  swift_testing_suite:
    name: "Swift Testing Suite"
    regex: "XCTestCase"
    message: "Use Swift Testing @Suite instead of XCTestCase"
    severity: warning

  swift_testing_test:
    name: "Swift Testing Test"
    regex: "XCTest"
    message: "Use Swift Testing @Test instead of XCTest methods"
    severity: warning

  swift_testing_expect:
    name: "Swift Testing Expect"
    regex: "XCTAssert"
    message: "Use Swift Testing #expect instead of XCTAssert"
    severity: warning

reporter: "github-actions-logging"  # Format for GitHub Actions
